use-bold=yes
prompt="  ──────▶ "
icon-theme=besgnulinux-drawing
icons-enabled=yes
delayed-filter-ms=500
match-mode=fzf
lines=40
width=34
tabs=8
horizontal-pad=80
vertical-pad=80
inner-pad=0
image-size-ratio=0.5

# Fuente personalizada
font=Caskaydia Cove Nerd Font:style=SemiBold Italic:size=14

[colors]
background=212921C0  
text=b87333ff           
border=b87333ff      
prompt=ffc340ff  

[border]
width=3              # Ancho del borde
radius=10            # Radio de borde suave

[dmenu]
mode=text            # Modo de texto para dmenu
exit-immediately-if-empty=no

[key-bindings]
cancel=Escape Control+g Control+c Control+bracketleft
execute=Return KP_Enter Control+y
prev=Up Control+p
next=Down Control+n
delete-prev=BackSpace Control+h
delete-next=Delete KP_Delete Control+d
