#Hacer que coja todos los subtítulos de la carpeta de la película
sub-auto=fuzzy

# Mantener el volumen al máximo si la peli se oye floja
volume-max=200

# Guardar la posición al cerrar (por si la ves en dos partes)
save-position-on-quit=yes

#Shift + g / Shift + f: Para aumentar o disminuir el tamaño de la letra.

#Ctrl + Shift + Izquierda/Derecha: Si por un casual los subtítulos van 
#un pelín desfasados (un segundo antes o después), 
#con esto los sincronizas al milisegundo sin cerrar la peli.
# Forzar que aparezca la barra de control al mover el ratón
osc=yes
# Permitir que el teclado funcione siempre
input-default-bindings=yes
# Que la ventana tenga bordes para poder manejarla mejor
border=yes
